workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: 3.27.0
      xcode: latest
    scripts:
      - name: Flutter clean and get
        script: |
          flutter pub cache clean --force
          flutter clean
          flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod repo update
          pod install
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign -t lib/main.dart
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - kontakt@koliberlux.pl