def firebase_sdk_version
  '11.0.0'
end

platform :ios, '15.0'

# Wymuszamy nagłówki modułowe globalnie
use_modular_headers!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Kluczowe biblioteki
  pod 'Firebase/Firestore', firebase_sdk_version
  pod 'Firebase/Auth', firebase_sdk_version
  pod 'Firebase/Core', firebase_sdk_version
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # Te flagi zmuszają Xcode do zobaczenia Firestore jako modułu
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['DEFINES_MODULE'] = 'YES'
    end
  end
end